queue_rules:
  - name: "default"
    conditions: []

  - name: "1_2"
    conditions: []

pull_request_rules:
  - name: Backport to stable
    conditions:
      - "base=master"
      - "label=backport: 1.2"
    actions:
      backport:
        branches:
          - "1.2"
        title: "[1.2] {{ title }}"
        body: "Backport of #{{number}} to `{{ destination_branch }}` branch."
        labels: ["backport", "mergeable"]

  - name: Merge queue
    conditions:
      - "base=master"
      - "label=mergeable"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: "default"

  - name: 1.2 branch merge queue
    conditions:
      - "base=1.2"
      - "label=mergeable"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: "1_2"

  - name: Automatic approval of 1.2 branch backports
    conditions:
      - "label=backport"
    actions:
      review:
        type: APPROVE
        message: Automatically approving 1.2 branch backports
